title: 14th Asia Pacific Orchid Conference 2023
url: https://www.apoc14.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#417505"
  secondary-color: "#f5a623"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: The 14th Asia Pacific Orchid Conference 2023 will be held from 16 –
  20 Aug 2023 at Singapore Expo (Hall 2)
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3sni4i0dncua3.amplifyapp.com
prod: https://master.d3sni4i0dncua3.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
